---
- hosts: self
  vars_files:
  - /etc/provisioning/vagrant-vars.yaml
  roles:
  - role: git
  - role: bash-environment
  - role: ansible-environment
  - role: vagrant-environment
  - role: docker
    vars:
      docker_users:
      - "{{ vagrant_user }}"
  - role: dist-upgrade
