---
- hosts: self
  vars_files:
  - /etc/provisioning/git-vars.yaml
  - /etc/provisioning/vagrant-vars.yaml
  roles:
  - role: dist-upgrade
  - role: ansible-environment
  - role: git-environment
  - role: vagrant-environment
  - role: build-essential
  - role: python3
  - role: docker
    vars:
      docker_compose_version: "1.21.2"
      docker_users:
      - "{{ vagrant_user }}"
  - role: sqlite
  - role: unzip
  - role: zip
