---
- name: Downloading installation ...
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh
    dest: ~/nvm_install.sh
    mode: u+rwx,go+rx-w
- name: Installing ...
  shell: ~/nvm_install.sh
  args:
    creates: ~/.nvm/nvm.sh
